### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by yeethuan** [Drexel-University-UXID/uxid-courses#10]
My margins in my Portfolio page and my Gallery page are inconsistent with each other. Additionally, the images are not centered and I do not know how to 
1. have images centered WITH left and right margins of 15px
2. images that scale with the screen
In my css they are all defined by "margin-left: 15px; and "margin-right: 15px;". I believe the issue stems from my horizontal images that are bigger than the screens causing a mandatory horizontal scroll. I do not know how to resolve either issues. 

  
    <h3>Asian Americans United</h3>
    <div class="container2">
        <img src="media/aau.webp" alt="AAU Project"><br>
        <p>
        I have been involved with AAU since working as a high school intern to learn about social justice issues and
        current events in the community. This summer, I worked as a program co-lead to curate a 6-week intensive high
        school summer program about social justice, community values, and racial identity. I facilitated sensitive
        conversations pertaining to Asian American history, Black and Asian solidarity, immigration, sexual orientation,
        gender identity, gentrification, and more. I oversaw and trained youths to learn how to interview individuals in
        the context of sensitive topics like those mentioned above for research purposes.
    </p>
    </div>

    <h3>Bloomberg Arts Internship at the Fabric Workshop and Museum</h3>
    <div class="container2">
        <img src="media/fwm-marlborough-cocktail.webp" alt="FWM"><br>
        <p>
            During my time as a Development Intern, I completed competitive analysis of 10+ museum membership programs to
            present and brainstorm ideas on improving in-house membership programs. I designed the official invitation for
            a formal gathering in collaboration with Marlborough Gallery. I arranged profile booklets for artists Henry Taylor
            and Ahmed Alsoudani. I also presented a final project on my fabric design print.
        </p>
    </div>

    <h3>Asian American Philadelphia Advocacy Conference</h3>
    <div class="container2">
        <img src="media/23-brochure.webp" alt="AAPAC"><br>
        <p>
        During my freshman year of college, I was on the leadership team for the Asian American Philadelphia Advocacy
        Conference (AAPAC) as a member of the Marketing Committee where I developed a strategic marketing plan and
        designed graphics to promote the event, resulting in an attendance of 80+ attendees; this was double the amount
        from previous years.
        </p>
    </div>
    
    
    
    
    /* PORTFOLIO CSS*/
h1 {
    font-family: verdana;
    color: #597692;
    font-size:3em;
    margin-left: 15px;
}

/* Relevant Experiences and Activities */
h2 {
    font-family: verdana;
    color: #CD6767;
    font-size: 22px;
    padding-top: 1em;
    margin-left: 15px;
}

/* Specific Experience Titles */
h3 {
    font-family:'Franklin Gothic Medium';
    color:#AE1414;
    margin-left: 15px;
    padding-top: 25px;
}

/* Normal Text */
p {
    font-family:verdana;
    color:#706A63;
    line-height: 1.5em;
    font-size: 1em;
    margin-left: 15px;
    margin-right: 15px;
    text-align: left;
}

/* Resume Button */
.container1 {
    padding-top: 2em;
    text-align: left;
    margin-left: 15px;
}

.button {
    padding: 10px 20px;
    font-size: 16px;
    font-family: sans-serif;
    text-decoration: none;
    background-color: #597692;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}
/* Resume Button End*/

/* images of Relevant Experiences and description text settings */
img {
    max-width: 100%;
    height: auto;
    margin-left: 15px;
    margin-right: 15px;
    text-align: right;
    width:max-content;
}

.container2 {
    padding-top: 0px;
    padding-bottom: 0px;
}
/* images of Relevant Experiences and description text settings */

**Comment by philsinatra** [comment]
Create issues in your project repository, not here in the class resources repo. Create a new issue and include a link to your live site in your repository. You can tag me (@philsinatra), and then I can review your issue and your project files.
