### ISSUE TITLE
HMTL Anchors Assignment

### ISSUE THREAD

**Issue by delacooke** [Drexel-University-UXID/uxid-courses#4]
Hi, I am having trouble finding an issue for programming an image tag that loads an image named logo.png that is up one directory, in a folder named ui. What should fill in the blank in the following code?   <img src="______">

I have: <img src="..ui/logo.png"> 

also for programming an anchor tag that should link to a file named intro.html in a directory named pages. What should fill in the blank in the following code? <a href="______">my link</a>

I have: <a href="pages/intro.html">my link</a>

Can you help me figure out why they are incorrect? Thanks!

**Comment by philsinatra** [comment]
The images in your post are not loading, and the links in your post circle back to this issue. Can you update your question with more details?
